definitions:
  global.Config:
    properties:
      captcha:
        description: "Captcha\n\t@Description:验证码配置"
        properties:
          expireTime:
            description: 验证码过期时间(seconds)
            type: integer
          sendEmail:
            description: 是否发送邮件验证码
            type: boolean
        type: object
      email:
        description: "Email\n\t@Description:Email配置"
        properties:
          from:
            description: 发件人邮箱
            type: string
          host:
            description: SMTP 服务器地址
            type: string
          port:
            description: SMTP 端口(默认 465)
            type: integer
          smtpPass:
            description: SMTP 密钥（开启SMTP时获取的密钥，而非邮箱密码）
            type: string
          smtpUser:
            description: SMTP 用户名(邮箱账号)
            type: string
        type: object
      jwt:
        description: "JWT\n\t@Description:JWT配置"
        properties:
          expire:
            description: JWT过期时间(hours)
            type: integer
          issuer:
            description: JWT签发者
            type: string
          secret:
            description: JWT密钥
            type: string
        type: object
      log:
        description: "Log\n\t@Description:\t日志配置"
        properties:
          directory:
            description: 日志目录
            type: string
          format:
            description: 日志格式 (json | text)
            type: string
          level:
            description: 日志级别 (debug | info | warn | error )
            type: string
          prefix:
            description: 日志前缀
            type: string
        type: object
      mysql:
        description: "Mysql\n\t@Description:Mysql数据库配置"
        properties:
          config:
            description: Mysql 高级配置
            type: string
          dbname:
            description: Mysql 数据库名称
            type: string
          host:
            description: Mysql 服务器地址
            type: string
          password:
            description: Mysql 密码
            type: string
          port:
            description: Mysql 服务器端口
            type: string
          username:
            description: Mysql 用户名
            type: string
        type: object
      qiniu:
        description: "Qiniu\n\t@Description:七牛云配置"
        properties:
          accessKey:
            description: 七牛云访问密钥
            type: string
          bucket:
            description: 空间名称
            type: string
          imgPath:
            description: 外链图片访问路径
            type: string
          secretKey:
            description: 七牛云私密密钥
            type: string
          useCdnDomains:
            description: 是否使用CDN上传加速
            type: boolean
          useHTTPS:
            description: 是否使用https
            type: boolean
          zone:
            description: 存储区域
            type: string
        type: object
      redis:
        description: "Redis\n\t@Description:Redis数据库配置"
        properties:
          addr:
            description: Redis 服务器地址:端口
            type: string
          db:
            description: Redis 数据库引索
            type: integer
          password:
            description: Redis 密码
            type: string
        type: object
      server:
        description: "Server\n\t@Description:\t服务器配置"
        properties:
          dbAutoMigrate:
            description: 数据库表结构是否自动迁移
            type: boolean
          dbLogMode:
            description: 数据库日志模式（silent | error | warn | info）
            type: string
          dbType:
            description: 数据库类型
            type: string
          mode:
            description: 服务器模式(debug | release)
            type: string
          port:
            description: 服务器端口号
            type: string
        type: object
      session:
        description: "Session\n\t@Description:Session配置"
        properties:
          maxAge:
            description: session 过期时间（seconds）
            type: integer
          name:
            description: session 名称
            type: string
          salt:
            description: session 盐值
            type: string
        type: object
      sqlite:
        description: "SQLite\n\t@Description:SQLite数据库配置"
        properties:
          dsn:
            description: SQLite 数据源名称（DSN）
            type: string
        type: object
      upload:
        description: "Upload\n\t@Description:文件上传配置"
        properties:
          ossType:
            description: OSS存储类型(local | qiniu)
            type: string
          path:
            description: 本地文件访问路径
            type: string
          size:
            description: 上传文件大小限制(字节)
            type: integer
          storePath:
            description: 本地文件存储路径
            type: string
        type: object
    type: object
  handle.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handle.LoginVO:
    properties:
      article_like_set:
        items:
          type: string
        type: array
      avatar:
        description: 头像最大长度1024字符，保存用户的头像
        type: string
      comment_like_set:
        items:
          type: string
        type: array
      created_at:
        type: string
      email:
        description: 邮箱最大长度30字符，保存用户的电子邮件地址
        type: string
      id:
        type: integer
      intro:
        description: 简介最大长度255字符，保存用户的简介
        type: string
      nickname:
        description: 昵称最大长度30字符，保存用户的昵称
        type: string
      token:
        description: 点赞 Set： 用于记录用户点赞过的文章，评论
        type: string
      updated_at:
        type: string
      website:
        description: 网站最大长度255字符，保存用户的网站等链接
        type: string
    type: object
  handle.RegisterReq:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 4
        type: string
    required:
    - email
    - password
    type: object
  handle.Response-any:
    properties:
      code:
        description: 业务状态码
        type: integer
      data:
        description: 响应数据
      message:
        description: 响应消息
        type: string
    type: object
  handle.Response-handle_LoginVO:
    properties:
      code:
        description: 业务状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/handle.LoginVO'
        description: 响应数据
      message:
        description: 响应消息
        type: string
    type: object
  handle.Response-string:
    properties:
      code:
        description: 业务状态码
        type: integer
      data:
        description: 响应数据
        type: string
      message:
        description: 响应消息
        type: string
    type: object
info:
  contact: {}
paths:
  /config:
    get:
      consumes:
      - application/json
      description: 获取配置信息
      parameters:
      - description: 配置信息
        in: body
        name: data
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/handle.Response-any'
      summary: 获取配置信息
      tags:
      - blog_info
    patch:
      consumes:
      - application/json
      description: 更新配置信息
      parameters:
      - description: 更新配置信息
        in: body
        name: data
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/handle.Response-any'
      summary: 更新配置信息
      tags:
      - blog_info
  /login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 登录
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/handle.LoginReq'
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/handle.Response-handle_LoginVO'
      summary: 登录
      tags:
      - UserAuth
  /logout:
    get:
      consumes:
      - application/json
      description: 退出登录
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/handle.Response-string'
      summary: 退出登录
      tags:
      - UserAuth
  /register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: 注册
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/handle.RegisterReq'
      produces:
      - application/json
      responses:
        "0":
          description: 返回空数组
          schema:
            $ref: '#/definitions/handle.Response-string'
      summary: 注册
      tags:
      - UserAuth
  /report:
    post:
      consumes:
      - application/json
      description: 用户登进后台时上报信息
      parameters:
      - description: 用户信息
        in: body
        name: data
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/handle.Response-any'
      summary: 上报用户信息
      tags:
      - blog_info
swagger: "2.0"
